[ylim]
analyze = [-0.1, 1.1]
L1_move = [-0.1, 1.1]
L1_rest = [-0.1, 1.1]
L1_walk = [-0.1, 1.1]
L1_groom = [-0.1, 1.1]
L1_other = [-0.1, 1.1]
ball = [-0.1, 1.1]
manipulation = [-0.1, 1.1]
annotation = [-0.1, 1.1]
stimulus = [-0.1, 1.1]
stimulus_core = [-0.1, 1.1]
calcium = [-5, 50]
predicted_calcium = [-1, 20]
calcium_norm = [-0.1, 1.1]
predicted_calcium_norm = [-0.1, 1.1]
L1C_flex = [10, 160]
vel_forward = [-5, 20]
vel_lateral = [-20, 20]
vel_rotational = [-300, 300]
[ytick]
analyze = [0, 1]
L1_move = [0, 1]
L1_rest = [0, 1]
L1_walk = [0, 1]
L1_groom = [0, 1]
L1_other = [0, 1]
ball = [0, 1]
manipulation = [0, 1]
annotation = [0, 1]
stimulus = [0, 1]
stimulus_core = [0, 1]
calcium = [0, 50]
predicted_calcium = [0, 1]
calcium_norm = [0, 1]
predicted_calcium_norm = [0, 1]
L1C_flex = [30, 90, 150]
vel_forward = [0, 20]
vel_lateral = [-20, 0, 20]
vel_rotational = [-300, 0, 300]